name: CFBlog Workflow with Robust Error Handling

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_search_xml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # ... 其他原有步骤 ...

    - name: Compare and Update if Different
      if: steps.check_file.outputs.exists == 'true'
      run: |
        set -e
        cmp --silent Data/search.xml Data/search_new.xml || (
          echo "Files differ. Updating..."
          mv Data/search_new.xml Data/search.xml
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git pull origin $GITHUB_REF --rebase # 添加拉取并变基操作以处理可能的冲突
          git add Data/search.xml
          git commit -m "Update search.xml with changes"
          git push origin HEAD:$GITHUB_REF || (
            echo "Push failed, possibly due to conflicts. Review and resolve manually."
            exit 1
          )
        ) || (
          echo "Comparison or update failed. Check the download and permissions."
          exit 1
        )

    # ... 其他原有步骤 ...

    # 完成步骤保持不变
    - name: Workflow Completion Marker
      if: always()
      run: echo 'Workflow finished. No changes made or all updates applied successfully.'
