name: CFBlog Workflow with Enhanced Logging and Retries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_search_xml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # ... 其他原有步骤 ...

    - name: Compare and Update if Different
      if: steps.check_file.outputs.exists == 'true'
      run: |
        set -e
        RETRIES=3
        until [ $RETRIES -eq 0 ]; do
          cmp --silent Data/search.xml Data/search_new.xml && {
            echo "Files are identical. Skipping further update actions."
            echo "::warning::No changes detected in search.xml."
            break
          } || {
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git pull origin $GITHUB_REF --rebase # 拉取并变基处理冲突
            git add Data/search.xml
            git commit -m "Update search.xml with changes"
            git push origin HEAD:$GITHUB_REF && {
              echo "Update successful."
              break
            } || {
              echo "::error::Push failed. Retrying in $(($RETRIES-1)) seconds."
              sleep 5
              ((RETRIES--))
            }
          }
        done
        [ $RETRIES -eq 0 ] && {
          echo "::error::Failed to update after $((3-$RETRIES)) retries. Manual intervention required."
          exit 1
        }

    # ... 其他原有步骤 ...

    - name: Workflow Completion Marker
      if: always()
      run: |
        if [ "${{ steps.compare_and_update_if_different.outcome }}" = "success" ]; then
          echo 'Workflow completed successfully. All updates applied or verified no changes needed.'
        elif [ "${{ steps.compare_and_update_if_different.outcome }}" = "failure" ]; then
          echo '::error::Workflow did not complete successfully. See previous steps for error details.'
        else
          echo 'Workflow finished without applying changes. No updates were necessary.'
        fi
