name: 'CFBlog'

on:
  workflow_dispatch:  # 手动触发事件保持不变
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 使用最新版本的 checkout 操作，确保兼容性和功能更新
      
    - name: Set up Node.js 16  # 设置 Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16  # 明确指定使用 Node.js 16 版本
      
    - name: Create directory and get search.xml
      env:
        CFBLOG_TOKEN: ${{ secrets.CFBLOG_TOKEN }}
        CFBLOG_HOST: ${{ secrets.CFBLOG_HOST }}
      run: |
        mkdir -p Data  # 确保文件夹存在
        curl "https://${CFBLOG_HOST}/admin/search.xml" -H "cfblog_token: ${CFBLOG_TOKEN}" > Data/search.xml  # 下载最新的 search.xml 文件
      
    - name: Check if files have changed
      id: check_changes
      run: |
        git diff --quiet --exit-code || echo "Files have changed"  # 检查是否有文件变更
      
    - name: Change to branch
      env:
        CFBLOG_BRANCH: ${{ secrets.CFBLOG_BRANCH }}
      run: |
        git switch -C $CFBLOG_BRANCH  # 切换到指定的分支，如果不存在则创建新分支
      
    - name: Commit and push changes
      if: steps.check_changes.outputs.result == 'true'  # 只有在文件有变更时才执行提交和推送
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add Data/search.xml
        git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')"  # 提交更新到 GitHub，包含时间戳
        git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
    - name: Done
      run: echo 'Workflow completed successfully'  # 完成工作流程的输出确认信息
