name: 'CFBlog'

on:
  workflow_dispatch:  # 手动触发事件保持不变
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 更新到最新版本，通常更佳的兼容性和功能
      
    - name: Set up Node.js 16  # 使用 Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16  # 明确指定使用 Node.js 16 版本
      
    - name: Create directory and get search.xml
      env:
        CFBLOG_TOKEN: ${{ secrets.CFBLOG_TOKEN }}
        CFBLOG_HOST: ${{ secrets.CFBLOG_HOST }}
      run: |
        mkdir -p Data  # 确保文件夹存在
        curl "https://${CFBLOG_HOST}/admin/search.xml" -H "cfblog_token: ${CFBLOG_TOKEN}" > Data/search.xml.tmp
        
        # 检查 search.xml 是否有变化，如果没有则跳到完成步骤
        if cmp -s "Data/search.xml.tmp" "Data/search.xml"; then
          echo "No changes in search.xml"
          rm Data/search.xml.tmp
          exit 0
        fi
        
        # 如果有变化，则覆盖原始文件并继续
        mv -f Data/search.xml.tmp Data/search.xml
      
    - name: Create directory and get sitemap.xml
      env:
        CFBLOG_TOKEN: ${{ secrets.CFBLOG_TOKEN }}
        CFBLOG_HOST: ${{ secrets.CFBLOG_HOST }}
      run: |
        mkdir -p Data  # 确保文件夹存在
        curl "https://${CFBLOG_HOST}/admin/sitemap.xml" -H "cfblog_token: ${CFBLOG_TOKEN}" > Data/sitemap.xml.tmp
        
        # 检查 sitemap.xml 是否有变化，如果没有则跳到完成步骤
        if cmp -s "Data/sitemap.xml.tmp" "Data/sitemap.xml"; then
          echo "No changes in sitemap.xml"
          rm Data/sitemap.xml.tmp
          exit 0
        fi
        
        # 如果有变化，则覆盖原始文件并继续
        mv -f Data/sitemap.xml.tmp Data/sitemap.xml
      
    - name: Change to branch
      env:
        CFBLOG_BRANCH: ${{ secrets.CFBLOG_BRANCH }}
      run: |
        git switch -C $CFBLOG_BRANCH  # 使用 git switch 命令替代 git checkout，这是较新的命令

    - name: Commit and push changes
      if: success()  # 只有在前面的步骤成功时才会执行
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add Data/search.xml Data/sitemap.xml
        git commit -m "Update search.xml and sitemap.xml from GitHub Action $(date +'%Y-%m-%d %H:%M:%S')"  # 修改自定义提交消息
        git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        
    - name: Done
      if: success()  # 只有在前面的步骤成功时才会执行
      run: echo 'Workflow completed successfully'
