name: 'CFBlog'

on:
  workflow_dispatch:  # 手动触发事件保持不变
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 更新到最新版本，通常更佳的兼容性和功能
      
    - name: Set up Node.js 16  # 使用 Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16  # 明确指定使用 Node.js 16 版本
      
    - name: Get search.xml and sitemap.xml
      env:
        CFBLOG_TOKEN: ${{ secrets.CFBLOG_TOKEN }}
        CFBLOG_HOST: ${{ secrets.CFBLOG_HOST }}
      run: |
        curl "https://${CFBLOG_HOST}/admin/search.xml" -H "cfblog_token: ${CFBLOG_TOKEN}" > search.xml
        curl "https://${CFBLOG_HOST}/admin/sitemap.xml" -H "cfblog_token: ${CFBLOG_TOKEN}" > sitemap.xml
      
    - name: Change to branch
      env:
        CFBLOG_BRANCH: ${{ secrets.CFBLOG_BRANCH }}
      run: |
        git switch -C $CFBLOG_BRANCH  # 使用 git switch 命令替代 git checkout，这是较新的命令

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "no changes"
          echo "::set-output name=changes::false"
        else
          echo "changes detected"
          echo "::set-output name=changes::true"
        fi
      
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Update from GitHub Action $(date +%Y-%m-%d)"
        git push -
